# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-19 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0002_auto_20160112_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='book',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
