# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-19 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0003_auto_20170319_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='permission',
        ),
    ]
