# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-29 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0006_auto_20170323_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='method',
            field=models.BooleanField(default=True),
        ),
    ]
